cc_test(
    name = "dispatcher",
    size = "small",
    srcs = glob(["*.cpp"]),
    deps = [
        "//src/fx/command/base",
        "//src/fx/command/forwarder",
        "//src/fx/command/help",
        "//src/fx/command/list",
        "//src/fx/command/version",
        "//src/fx/dispatcher",
        "//src/fx/result",
        "@com_google_googletest//:gtest_main",
    ],
)
