name: ci
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:    
      - master
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos-x86
          - os: ubuntu-20.04
            platform: linux-x86
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Bazel Build
        run: bazel build //... --platforms=//:${{ matrix.platform }}
      - name: Bazel Test
        run: bazel test //... --platforms=//:${{ matrix.platform }}
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: clang-format & clang-tidy
        run: bazel build //... --config tidy-test
      - name: Bazel Lint
        run: bazel run //tools/format:buildifier-test
